language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  # must not be executed in parallel
  - cargo test -- --ignored --test-threads=1 add_get_remove_tasks
  - cargo test -- --ignored pids::tests::test_subsystem_current
  # (temporarily) overrides the root cgroup
  - cargo test -- --ignored release_agent
  - cargo test -- --ignored memory_pressure_enabled
