[package]
name = "cgroups"
version = "0.2.0"
edition = "2018"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]
license = "MIT OR Apache-2.0"

description = "Native Rust crate for operating on cgroups"
repository = "https://github.com/orgovicia/controlgroup-rs"
readme = "README.md"

exclude = [".gitignore", ".travis.yml"]

[badges]
travis-ci = { repository = "ordovicia/controlgroup-rs" }

[dependencies]

[dev-dependencies]
num_cpus = "1.10.1"
